Spelling
knop-project/knop pull request #135
Opened 2017-11-30 06:10 UTC by jsoref

Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`

found in: github/linguist#3923

2017-11-30 08:14 UTC, stevepiercy commented
This PR requires some cleanup and review before being merged. It does a good job of catching common misspellings in comments and narrative documentation, but there are some places within code where the suggested corrections are wrong.

2017-11-30 08:46 UTC, johansolve commented
This is likely an automated commit by jsoref's spelling tool. I think we need to cherrypick it. 
But I'm a bit shocked by all my spelling errors :)

2017-11-30 12:25 UTC, jsoref reviewed
It's all manually driven. Which code things are problematic? I was somewhat concerned about queryable, but...

2017-12-13 10:06 UTC, stevepiercy requested changes
Thanks for the contribution. Please make the requested changes, and I will merge them.

2017-12-13 10:06 UTC, stevepiercy commented on docs/source/knop_database.rst
> +      :param trait_queryable input:
These two changes should be reverted.

2017-12-13 10:06 UTC, stevepiercy commented on docs/source/knop_nav.rst
> +      :param trait_queryable input:
These two changes should be reverted.

2017-12-13 10:06 UTC, stevepiercy commented on knop8/LassoLibraries/knop.lasso
This file `knop8/LassoLibraries/knop.lasso` and all the changes in it should be reverted. It is generated automatically from the other files.

2017-12-13 10:06 UTC, stevepiercy commented on knop8/source/_ctype/form.inc
> +2007-01-19	JS	Adds renderform: -legend to be able to group form fields at render time
Should be "Added".

2017-12-13 10:06 UTC, stevepiercy commented on knop9/knoplibs/knop_database.lasso
> +	protected scrubKeywords(input::trait_queryable)::trait_forEach => {
revert

2017-12-13 10:06 UTC, stevepiercy commented on knop9/knoplibs/knop_nav.lasso
> +	protected scrubKeywords(input::trait_queryable)::trait_forEach => {
revert

2017-12-14 09:25 UTC, jsoref commented
@stevepiercy : I believe i've addressed your concerns

2017-12-14 09:44 UTC, stevepiercy approved these changes

2017-12-14 09:47 UTC, merged

2017-12-14 09:47 UTC, stevepiercy commented
Thank you!